site_name: Documentación del Método RK4 

theme:
  name: "material"

nav:
  - Introducción: index.md
  - Explicación: explanation.md
  - Tutorial: tutorials.md
  - Referencia de Funciones: reference.md

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
